### ISSUE TITLE
No cursor in Playground

### ISSUE THREAD

**Issue by thewatts** [XVimProject/XVim#622]
I'm new to XCode, as well as XVim, but I noticed that there isn't a cursor in Normal mode (at least, when I'm using this with XCode 6GM).

As a side note - thanks for a killer plugin!
##

**Comment by keith** [comment]
I'm still seeing this issue in the release version of Xcode 7

**Comment by JugglerShu** [comment]
Use `set blinkcursor` option for now. I'm investigating the problem.

**Comment by carrigmore** [comment]
has this issue been fixed?

**Comment by nickkjordan** [comment]
I think this issue is fixed in XCode 7.2

**Comment by dkinzer** [comment]
I'm on  Xcode  7.3.1 and issue is still present in Playground and the .xvimrc work around is not working form me.

**Comment by JuliaNocera** [comment]
Hello! Thanks so much for this plugin! 

I am also seeing this issue in Xcode 8 beta and the work around is not working for me either

**Comment by danzimm** [comment]
@dkinzer I'm on Xcode 7.3.1 and ran into this issue. I cloned the repo and checked out the master branch at d0ee97d2a136d723d4a7ce4f9b515a8515db1d9f and the bug appears to have disappeared (meaning the cursor reappeared)

**Comment by boboRAY** [comment]
@danzimm cursor still disappear at `d0ee97d` on my Xcode (7.3.1)

**Comment by ryanchou1991** [comment]
+1  on my Xcode (7.3.1) I can't see the cursor in my playground

**Comment by NextSeason** [comment]
No way to fix it ?

**Comment by pebble8888** [comment]
I fixed it in `dev7` branch for Xcode7.3.1.
When you find a problem, plz report it.

**Comment by wiseviewbuilder** [comment]
I can confirm @pebble8888's fix works.

**Comment by humblehacker** [comment]
I can confirm that @pebble8888's fix works.

**Comment by mdm508** [comment]
Hi, I am sorry for the beginner questions, but is this change already part of the master? Cause it is still not working for me. I'm new to git and just wondering how I can get the change.

**Comment by haaakon** [comment]
This happens for me in XCode 8

**Comment by amandogra** [comment]
This issue is still there for XCode Version 8.0 (8A218a).
I've tried adding `set blinkcursor` to .xvimrc, but it is not helping.

**Comment by amandogra** [comment]
```
XVim revision : 
OS Version : Version 10.11.5 (Build 15F34)
Xcode Version : 8.0

--- .xvmrc ---
set blinkcursor


--------------
```
has the issue

**Comment by haaakon** [comment]
@JugglerShu Does not seem that the fixes for XCode 7.x fixes the problem that has reappeared for XCode 8.

**Comment by pebble8888** [comment]
I confirmed `dev7` branch doesn't fix the problem in Xcode8.
Please try `pebble8888/develop` branch.
I just cherry-picked @JessThrysoee's work.

**Comment by jakecraige** [comment]
I'm seeing this too. @pebble8888 installing your branch worked for me 👍

**Comment by amandogra** [comment]
Thanks @pebble8888 your develop branch is showing the cursor.

https://github.com/pebble8888/XVim/tree/develop

**Comment by Tylerc230** [comment]
@pebble8888 I pulled your branch. The cursor now appears for me in normal mode but all the text on the current line disappears. When I move the cursor to a different line, the text reappears.

**Comment by shengithub** [comment]
@pebble8888 Thanks so much. It works my cursor is back :)

**Comment by cedricwzy** [comment]
@pebble8888 Thanks man, it's working like a charm.

**Comment by Tylerc230** [comment]
@pebble8888 This is working for me now. @JugglerShu Any chance we can get this merged into master?

**Comment by JugglerShu** [comment]
@Tylerc230 Yes. I'll merge it as soon as possible.

**Comment by jianghaoyuan2007** [comment]
@amandogra It works for me. Thanks so much!

**Comment by daniel-noul** [comment]
@pebble8888 it works for me xcode 8.1. thanks~

**Comment by rudedogg** [comment]
PR https://github.com/XVimProject/XVim/pull/1016, trying to reference the PR in issues to make it easier for @JugglerShu to close them once it's merged.

**Comment by jmcclell** [comment]
I still experience this problem even with the patch from pebble8888/XVimProject on xcode 8.2.1, alas.

I uninstalled the previous version, rebuilt and installed, and I do get a cursor. But as soon as I view the timeline of a MetalKit view the cursor disappears in all of my editors and doesn't return.

**Comment by MarcoSero** [comment]
I'm still seeing the issue (Xcode 8.2.1)
